background=#2b2b2b
foreground=#c8d7ec
caret=#ffffff
selection=#4d4870
currentLine=#3c3f41
matchedBracket.bg=#2f70ff
matchedBracket.border=#a0a0a0

token.string=#95bf5e
token.number.int=#6eb1ff
token.number.float=#c8d7ec
token.boolean=#ff5b5b
token.backquote=#a0a0a0
token.char=#edbd5b
token.separator=#c8d7ec
token.variable=#edbd5b
token.reservedWord=#edbd5b
token.reservedWord2=#ef8a8a
token.commentKeyword=#ffffff

scrollbar.bg=#3c3f41

font.family=JetBrains Mono
font.size=20

response.token.char=#dd6d12
response.token.reservedWord=#ffab55
