background=#ffffff
foreground=#2b2b2b
caret=#000000
selection=#b3d7ff
currentLine=#f2f2f2
matchedBracket.bg=#b3d7ff
matchedBracket.border=#808080

token.string=#067d17
token.number.int=#1750eb
token.number.float=#2b2b2b
token.boolean=#cc0000
token.backquote=#808080
token.char=#9e6b00
token.separator=#2b2b2b
token.variable=#9e6b00
token.reservedWord=#9e6b00
token.reservedWord2=#cc4444
token.commentKeyword=#000000

scrollbar.bg=#e8e8e8

response.token.char=#b85c00
response.token.reservedWord=#b85c00
